### PR TITLE
feat: astro-font - optimize fonts & prevent CLS

### PR DESCRIPTION
**Pull request by rishi-raj-jain**
- feat: https://www.launchfa.st/features/astro-font
- fix: 710 is not a valid font weight afaik: https://developer.mozilla.org/en-US/docs/Web/CSS/font-weight

### CODE REVIEW

**Comment by heycassidy** [comment]
@rishi-raj-jain Thanks for the PR, astro-font looks very cool, I'm seeing a huge improvement, especially with the headings!

Btw, Syne is a [variable font](https://fonts.google.com/knowledge/glossary/variable_fonts) that supports font-weight as any integer between 400 and 800.

Next/font does automatic self hosting, but it looks like astro-font does not? That is one of the big reasons I am using https://fontsource.org/ currently.

If I can get self-hosting and variable fonts working with astro-font, then this looks like a great solution. I will play around with this at some point this week, thanks!

**Comment by heycassidy** [comment]
@rishi-raj-jain Looks like variable fonts work without any trouble! The weight property in the config is unnecessary for variable fonts. Automatic self-hosting would be fantastic, but manual self hosting is just fine. Thanks for all the work porting this from NextJS! merging this PR now

**Comment by rishi-raj-jain** [comment]
> @rishi-raj-jain Looks like variable fonts work without any trouble!

That's lovely!

> The weight property in the config is unnecessary for variable fonts.

Oh alright, let me improve the library to make it optional... Appreciate your feedback!

> Automatic self-hosting would be fantastic, but manual self hosting is just fine. Thanks for all the work porting this from NextJS! merging this PR now

My pleasure! Right now the self-hosting does work with `fetch: true` flag (https://github.com/rishi-raj-jain/astro-font/blob/master/packages/astro-font/utils.ts#L22). I'll look into updating the docs to mention that more...

Totally appreciate your feedback, time and love to the library!

**Comment by heycassidy** [comment]
@rishi-raj-jain Ah, I'll give that `fetch: true` a shot, thanks!
And btw, I'm noticing an issue in Safari where the Syne font is too bold that seems to be resolved by using `weight: '400 800'` for that font. I'm guessing Safari needs to know the range of weights that a variable font can use, so I think I'm wrong about `weight` being optional for variable fonts

**Pull request merged**
